### ISSUE TITLE
Elemental eSports Retake server crash random after a day or two

### ISSUE THREAD

**Issue by ELT-SadikReis** [MikkelDK/LHELT#4]
Like the title says the server just random crashes after a day or two.

**Comment by MikkelDK** [comment]
it was restarted 05:00 > so lets see, when it will crash. because daemon has been restarted.

**Comment by ELT-SadikReis** [comment]
It crashed again :)

**Comment by MikkelDK** [comment]
> It crashed again :)

Try update the newest sourcemod, if you can via FTP. ;) (Remember Linux version)

**Comment by ELT-SadikReis** [comment]
Seems like it fixed the problem i havnt seen a crash since i updated the sourcemod.

**Comment by ELT-SadikReis** [comment]
Seems like it worked updating sourcemod. 
-Locked
