### ISSUE TITLE
Panel problem showing uptime for servers

### ISSUE THREAD

**Issue by ELT-SadikReis** [MikkelDK/LHELT#5]
Panel is not showing if the server is up or down plus the schedule wont work

**Comment by MikkelDK** [comment]
There can be some issues with the "crontab" i have try edited on it. and we will see about it works.

***\ about the "panel is not show server up/down /***

it's because the VPS has been down, because maintenance from datacenter. - Dunno when it will works.

**Comment by ELT-SadikReis** [comment]
Seems like the problem is solved for now.
